### ISSUE TITLE
As a developer I want some aggregate tasks

### ISSUE THREAD

**Issue by rydahhh** [Fortune-Transportation/fortune-front-end#28]
Create the following aggregate tasks:
* [x] Test - Runs tests #29
* [x] Dev - Starts dev environment #30
* [x] Start - Calls dev
* [x] Prod - Compiles project for distribution #31

Parent: #1
